pipeline{
	agent {
		kubernetes {
      
            defaultContainer 'jnlp'
            cloud 'dev-cluster'	
            yamlFile 'jenkins/build.yaml'
      
        }
	}
	environment {
        IMAGE   	= "mjack98/devops_task"
        REPO_TAG		= "python_1.0.${BUILD_NUMBER}"
        NAMESPACE		= "neom-ai-trainingapp"
        REPO_BRANCH_NAME	= "helm"
        REPO_GIT_CREDENTIALS	= "Github"
        HELM_REPO_BRANCH_NAME	= "helm"
        HELM_REPO_URL= "github.com/mjack98/helm_charts.git"
        HELM_DIR = "helm_charts/python_app"
        HELM_VALUE_YAML="values.yaml"
        HELM_APP_NAME="python_app"
        }
	stages{
		stage("Image Build and Push "){
			steps {
				container('podman') {
					sh  "podman build . -t ${IMAGE}:${REPO_TAG}"			
					sh "podman push ${IMAGE}:${REPO_TAG}"
					sh "podman tag ${IMAGE}:${REPO_TAG} ${IMAGE}:latest"
					sh "podman push ${IMAGE}:latest"
					
				}
			}
		}
		stage('update helm chart'){
      steps{
        dir('Helm') {
          
              withCredentials([usernamePassword(credentialsId: "${REPO_GIT_CREDENTIALS}",
													usernameVariable: 'USERNAME',
													passwordVariable: 'PASSWORD')]) {
                
                sh '''git clone https://${USERNAME}:${PASSWORD}@${HELM_REPO_URL}
                      sed -i "s/python_.*/${REPO_TAG}/g" ${HELM_DIR}/${HELM_VALUE_YAML}
                      cd ${HELM_DIR} 
                      git status
                      git config --global user.email ${USERNAME}
                      git config --global user.name ${USERNAME}
                      git remote rename origin destination
                      git remote add origin https://${USERNAME}:${PASSWORD}@${HELM_REPO_URL}
                      git add .
                      git commit -m 'tag update'
                      git push origin ${HELM_REPO_BRANCH_NAME}
                  '''
				}
      }

    }

		stage("Helm"){
			steps {
				container('helm') {
					dir('Helm') {
			
              sh "ls && helm -n ${NAMESPACE} upgrade --install ${HELM_APP_NAME} ./${HELM_DIR}/ -f ./${HELM_DIR}/${HELM_VALUE_YAML} " 
          
					}
				}
			}
		}
	}
}
}